### ISSUE TITLE
[bug] protobuf needs downgrade?

### ISSUE THREAD

**Issue by alenknight** [melMass/comfy_mtb#101]
### Describe the bug

getting an error when i run comfyui - tried doing the reqs_windows.txt from comfy_mtb folder... no luck.  

```
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-09-25 03:02:08.299117
Total VRAM 24576 MB, total RAM 32704 MB
xformers version: 0.0.21
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_management.py", line 211, in <module>
    import accelerate
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\__init__.py", line 142, in <module>
    from .megatron_lm import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Failed to execute startup-script: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\prestartup_script.py / Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   2.2 seconds (PRESTARTUP FAILED): C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\AI\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .utils import is_tokenizers_available
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\AI\ComfyUI>pause
Press any key to continue . . .
```

### Reproduction

1. run comfyui statup....
2. error occurs right away.  
can't load comfy

### Expected behavior

expected to see comfyui... but it's unable to load

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-09-25 03:02:08.299117
Total VRAM 24576 MB, total RAM 32704 MB
xformers version: 0.0.21
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_management.py", line 211, in <module>
    import accelerate
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\__init__.py", line 142, in <module>
    from .megatron_lm import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Failed to execute startup-script: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\prestartup_script.py / Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   2.2 seconds (PRESTARTUP FAILED): C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\AI\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .utils import is_tokenizers_available
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\AI\ComfyUI>pause
Press any key to continue . . .
```

**Comment by melMass** [comment]
closed by: https://github.com/melMass/comfy_mtb/commit/5dfea51dd8db2a4829e559eadeda22374b51c8a4
