### ISSUE TITLE
[bug]  MTB Crashes ComfyUI

### ISSUE THREAD

**Issue by JranZu** [melMass/comfy_mtb#103]
### Describe the bug

After updating comfyUI no longer loads when I am using your mod, crashes during start or when loading a workflow that uses MTB

### Reproduction

Update MTB to the latest version
attempt to run ComfyUI

### Expected behavior

ComfyUI loads

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 416, in get_object_info
    out[x] = node_info(x)
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\generate.py", line 209, in INPUT_TYPES
    cls.CACHE_FONTS()
  File "D:\AI Tools\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\generate.py", line 193, in CACHE_FONTS
    fonts.extend(comfy_dir.glob(f"**/{extension}"))
  File "pathlib.py", line 1034, in glob
  File "pathlib.py", line 493, in _select_from
  File "pathlib.py", line 440, in _select_from
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI Tools\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\mtb'
```

**Comment by melMass** [comment]
You can try again now in master! I now use a new functionality of Comfy to declare the web extensions and removed the install script so the setup should be much easier now.
A proper release will be done later today or tomorrow: https://github.com/melMass/comfy_mtb/pull/109

**Comment by JranZu** [comment]
Thanks, everything seems to be working again.
