### ISSUE TITLE
[bug]  'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by youcanyoubing** [melMass/comfy_mtb#107]
### Describe the bug

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Lam-master module for custom nodes: No module named 'modelscope'
[comfy_mtb] | WARNING -> Web extensions folder at C:\ComfyUI_windows_portable\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 70, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 5, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 147, in <module>
    nodes, failed = load_nodes()
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 85, in load_nodes
    nodes_failed.extend(extract_nodes_from_source(filename))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 36, in extract_nodes_from_source
    source_code = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1131: illegal multibyte sequence

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: 'gbk' codec can't decode byte 0x92 in position 1131: illegal multibyte sequence

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Lam-master module for custom nodes: No module named 'modelscope'
[comfy_mtb] | WARNING -> Web extensions folder at C:\ComfyUI_windows_portable\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 70, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 5, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 147, in <module>
    nodes, failed = load_nodes()
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 85, in load_nodes
    nodes_failed.extend(extract_nodes_from_source(filename))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 36, in extract_nodes_from_source
    source_code = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1131: illegal multibyte sequence

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: 'gbk' codec can't decode byte 0x92 in position 1131: illegal multibyte sequence
```

**Comment by youcanyoubing** [comment]
Failed to load properly after installation

**Comment by melMass** [comment]
How did you install it?
It looks like it's interpreting ascii files as binary which is strange.
Installation is being simplified by a lot, some nodes deprecated, it should be ready by tomorrow

**Comment by youcanyoubing** [comment]
I previously downloaded the source code under custom_nodes can not be used, and all deleted with ComfyUI-Manager installation still can not be used
