### ISSUE TITLE
Error occurred when executing Deep Bump (mtb):

### ISSUE THREAD

**Issue by fredlef** [melMass/comfy_mtb#144]
### Describe the bug

Text from error:

Error occurred when executing Deep Bump (mtb):  int() argument must be a string, a bytes-like object or a real number, not 'Image'  File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 155, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 85, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 78, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/fredlefevre/AI/ComfyUI/custom_nodes/comfy_mtb/nodes/deep_bump.py", line 283, in apply in_img = np.transpose(image, (2, 0, 1)) / 255 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<__array_function__ internals>", line 200, in transpose File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 668, in transpose return _wrapfunc(a, 'transpose', axes) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc return _wrapit(obj, method, *args, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit result = getattr(asarray(obj), method)(*args, **kwds) ^^^^^^^^^^^^

### Expected behavior

I have two installs - one in comfyui portable and one in comfyui on Mac M3.  This is occurring only on Mac M3.

### Operating System

Mac

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fredlefevre/AI/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fredlefevre/AI/ComfyUI/custom_nodes/comfy_mtb/nodes/deep_bump.py", line 283, in apply
    in_img = np.transpose(image, (2, 0, 1)) / 255
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in transpose
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 668, in transpose
    return _wrapfunc(a, 'transpose', axes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
                     ^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

Prompt executed in 0.04 seconds
```

**Comment by fredlef** [comment]
Not sure why but it started working.  Temporary glitch maybe.

**Comment by fredlef** [comment]
closed
