### ISSUE TITLE
[bug] install script fails on FILM module downloads

### ISSUE THREAD

**Issue by baardev** [melMass/comfy_mtb#153]
### Describe the bug

"python scripts/download_models.py" crashes on FILM module.  This is a new "issue" as a few months ago, I installed them with no problem.  I tried installed from the Manager and manually, with the same results.

### Reproduction

1) Clean install of ComfyUI on Linux/CUDA 11.8/Python 3.12.0
2) git clone https://github.com/melMass/comfy_mtb in custom_nodes
3) pip install -r comfy_mtb/requirements.txt
4) cd comfy_mtb && python scripts/download_models.py -y

This is where it crashes

### Expected behavior

error-free install.

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
(comfy) ➜  custom_nodes git:(master) ✗ cd comfy_mtb
(comfy) ➜  comfy_mtb git:(main) python scripts/download_models.py             
Checkpoint 'deepbump256.onnx' for DeepBump already exists in '/home/jw/store/src/ComfyUI/models/deepbump'
Checkpoint 'detection_mobilenet0.25_Final.pth' for Face Swap already exists in '/home/jw/store/src/ComfyUI/models/insightface'
Checkpoint 'detection_Resnet50_Final.pth' for Face Swap already exists in '/home/jw/store/src/ComfyUI/models/insightface'
Checkpoint 'inswapper_128.onnx' for Face Swap already exists in '/home/jw/store/src/ComfyUI/models/insightface'
Checkpoint 'GFPGANv1.3.pth' for GFPGAN (face enhancement) already exists in '/home/jw/store/src/ComfyUI/models/face_restore'
Checkpoint 'GFPGANv1.4.pth' for GFPGAN (face enhancement) already exists in '/home/jw/store/src/ComfyUI/models/face_restore'
Choose models to download:
1. FILM: Frame Interpolation for Large Motion
Enter the numbers of the models you want to download (comma-separated):
>> 
Downloading FILM: Frame Interpolation for Large Motion...
Retrieving folder contents
Retrieving folder 1Cv62KmMLcUFGAu8jXumtt94QYBHwA0Ub L1
Retrieving folder 1WGIjO41vWIkQbT17YWcLbQhvY2kH1LoX saved_model
Retrieving folder 1X2JkL39G1mRcX5OFmM2NBTp0g364WjzN assets
Processing file 1HxAfoDIkJs9HUT6GmyHeiO4NDFtBhQKO keras_metadata.pb
Processing file 1WPHyhqRmIhpsCCAuWmlE2j_VHPe6c4eR saved_model.pb
Retrieving folder 1DtiXZuaQbVvEBiZ9Xd9uYAZV5d_9M8cI variables
Processing file 19CNAIFt59brxAG_3ihKGYrjRozEQADun variables.data-00000-of-00001
Processing file 1jvMCG321Ws0WswWjZPSiYudrUWYvP10l variables.index
Retrieving folder 153dvxVSAcsNv1cyHVJySYZ-Twchm4Jdi Style
Retrieving folder 1i9Go1YI2qiFWeT5QtywNFmYAA74bhXWj saved_model
Retrieving folder 1NSex_z_Mm13nobMRDyS6JeXLPhW3bREz assets
Processing file 1dT85Z-HyYsiUgIQbOgYFjwWPOw8en1RC keras_metadata.pb
Processing file 1nfi15im3LQvCx84ZRiNcfMuodDkRL_Ei saved_model.pb
Retrieving folder 1s9pbFx_bSbinhx5PChJwZqPsyRIlehmZ variables
Processing file 1_oyM-LBAK9o7-bNWf1jG8VvBYeqpmSUr variables.data-00000-of-00001
Processing file 1ceC2kbJs3U1dMMrp4hNIpoHRFxO33SFC variables.index
Retrieving folder 1wE7DKSncIxnSNgYmMDfucCpnxXFcI_6S VGG
Retrieving folder 1GhVNBPq20X7eaMsesydQ774CgGcDGkc6 saved_model
Retrieving folder 1OmIh0a1m2yeBg0vrc9uL1aVbSvwrK6QA assets
Processing file 1-KW5CVihmeiiMki9fIqwUfsnrVJyLdyn keras_metadata.pb
Processing file 11nvcQvf5n9JMrryvIPfypYEbRYz_1egM saved_model.pb
Retrieving folder 11TJyMo3c5YR48gzMRdzbitpBlm0MQbdu variables
Processing file 1Cke9KRsEW3s50jq3RULvYbUoEY8v--zN variables.data-00000-of-00001
Processing file 1QsBtJFG9GLcjprjgnf6R-eQJq3k6mWnN variables.index
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Traceback (most recent call last):
  File "/home/jw/store/src/ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py", line 205, in <module>
    main(models_to_download, args.yes)
  File "/home/jw/store/src/ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py", line 192, in main
    download_model(download_url, destination)
  File "/home/jw/store/src/ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py", line 61, in download_model
    download_model(url, destination)
  File "/home/jw/store/src/ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py", line 85, in download_model
    gdown.download_folder(download_url, output=destination, resume=True)
  File "/home/jw/.conda/envs/comfy/lib/python3.12/site-packages/gdown/download_folder.py", line 286, in download_folder
    filename = download(
               ^^^^^^^^^
  File "/home/jw/.conda/envs/comfy/lib/python3.12/site-packages/gdown/download.py", line 243, in download
    filename_from_url = m.groups()[0]
                        ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by baardev** [comment]
p.s.  I forgot to select my OS and can't edit, but this is on Arch Linux, not Windows.

**Comment by melMass** [comment]
Hi,

These are considered [optional nodes](https://github.com/melMass/comfy_mtb?tab=readme-ov-file#optional-nodes) now (mostly for Windows users actually).

On Linux you should just need tf:

**FROM THE PYTHON ENV OF COMFY**:
```sh
python -m pip install tensorflow
```

**Comment by melMass** [comment]
Ah your issue is about the download, it seems to be an upstream [issue](https://stackoverflow.com/questions/77798990/error-during-download-nonetype-object-has-no-attribute-groups)

**Comment by melMass** [comment]
It should be fixed, you will need to uninstall my fork of gdown and rerun `pip install -r requirements` for it to update properly and the issue should be solved (then you will need tf as explained earlier)
