### ISSUE TITLE
[feat] about note+

### ISSUE THREAD

**Issue by za-wa-n-go** [melMass/comfy_mtb#185]
### Describe the problem

[ERROR] An error occurred while retrieving information for the 'Note Plus (mtb)' node.
Traceback (most recent call last):
  File "X:\aiart\Data\Packages\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "X:\aiart\Data\Packages\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: 'str' object has no attribute 'INPUT_TYPES'

### Describe the solution you'd like

I'm sorry, I understand this is outside of the usual support, but I would appreciate your help.

I'm trying to create a node that only extracts Note+ nodes because the mtb nodes are too many to handle. I managed to get it to work, but I get the error. What is needed here?

**Comment by za-wa-n-go** [comment]
sorry yes!
