### ISSUE TITLE
comfy_mtb kills WD14 Tagger [bug] 

### ISSUE THREAD

**Issue by dynatron832** [melMass/comfy_mtb#188]
### Describe the bug

if i install the MTB nodes my WD14 tagger (https://github.com/pythongosssss/ComfyUI-WD14-Tagger) goes to "IMPORT FAILED" at comfy startup. at the moment i use comfy v0.0.1 but this happened also a version earlier.
repairing reinstalling dont help. tagger stayes broken at loadup.

comfy complaining with a few errors at startup. looks like the "onnxruntime_gpu-1.18.1.dist-info" is the problem.

>Traceback (most recent call last):
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\ComfyUI\nodes.py", line 1931, in load_custom_node
>    module_spec.loader.exec_module(module)
>  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\__init__.py", line 4, in <module>
>    from .wd14tagger import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 10, in <module>
>    import onnxruntime as ort
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
>    raise import_capi_exception
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
>    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "F:\ComfyUI_v0.0.1_MK3_Testing\python_embeded\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in ><module>
>    from .onnxruntime_pybind11_state import *  # noqa

internal status (http://127.0.0.1:8188/mtb/status) of MTB tells me this as Failed to load
MTB_DeepBump	-
MTB_FaceSwap	-
MTB_FilmInterpolation	-
MTB_ImageRemoveBackgroundRembg	-
MTB_LoadFaceAnalysisModel	-
MTB_LoadFaceSwapModel	-
MTB_LoadFilmModel	-

the only way to get both working is to delete the onnxruntime and WD14. after that reinstalling WD14 brings the propper onnxruntime. 

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report, my guess is that you are now using CUDA 12 and it needs a special index to be specified in that case... I'll test a few things to see the best approach here.
In the meantime you can follow these instructions: https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x

Using the python/pip from comfy embed (at `F:\ComfyUI_v0.0.1_MK3_Testing\python_embeded\bin` I think)

**Comment by dynatron832** [comment]
thx for having a look. i would guess its the tagger which dont wanna work with the newer/other onnx stuff. maybe it gets an update sometimes.
