### ISSUE TITLE
[bug] fails to register

### ISSUE THREAD

**Issue by za-wa-n-go** [melMass/comfy_mtb#2]
Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1422, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 48, in <module>
    "Int to Number (mtb)": IntToNumber,
NameError: name 'IntToNumber' is not defined

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: name 'IntToNumber' is not defined

**Comment by za-wa-n-go** [comment]
Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1422, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 59, in <module>
    "Modulo (mtb)": Modulo,
NameError: name 'Modulo' is not defined

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: name 'Modulo' is not defined

**Comment by melMass** [comment]
Thanks for reporting! I think you are the first user!
I will look into it today I need to simplify the install process/ instructions

**Comment by melMass** [comment]
@za-wa-n-go can you try again? These should be fixed now

**Comment by za-wa-n-go** [comment]
I tried, but when I started Comfy after importing the latest, I got the following error

Traceback (most recent call last):.
  File "C:\Product\ComfyUI\nodes.py", line 1422, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 52, in <module
    os.symlink((here / "web"), web_mtb.as_posix())
OSError: [WinError 1314] Client does not have the requested privilege. : 'C:\Product\\\ComfyUI\\\custom_nodes\\\comfy_mtb\web' -> 'C:/Product/ComfyUI/web/extensions/mtb'

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: [WinError 1314] Client does not have the requested
The client does not have the requested privileges. : 'C:\Product\\\ComfyUI\\custom_nodes\\comfy_mtb\web' -> 'C:/Product/ComfyUI/web/extensions/mtb'

Translated with www.DeepL.com/Translator (free version)

**Comment by melMass** [comment]
Closing as it is now just ignoring it and I added instructions to the readme, thanks for the report!
