### ISSUE TITLE
[bug] The input/output panel should be hidden if not authorized

### ISSUE THREAD

**Issue by melMass** [melMass/comfy_mtb#214]
### Describe the bug

I forgot to test it in restricted mode (the default) so it looks buggy:

<img width="446" alt="image" src="https://github.com/user-attachments/assets/231a59c4-e9a1-4947-9f32-eae77983e37d">

### Reproduction

- Do not set `MTB_EXPOSE`
- Panel is empty as the endpoint reject the request

### Expected behavior

Completely hide it when restricted

### Operating System

Windows (Default)

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
Not relevant
```

### Additional context

This should all be documented somewhere

**Comment by Lalimec** [comment]
How can i "authorize the session" or expose? Is it because i ve enabled user login in my ComfyUI?

![image](https://github.com/user-attachments/assets/905717de-8943-44cc-90b2-ad3de8308d20)


```
Debug:
Disabled

Exposed:
False
```

```
Prestartup times for custom nodes:
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/rgthree-comfy
  51.6 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Manager
Total VRAM 22503 MB, total RAM 63592 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10G : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/ubuntu/ai/ComfyUI/web
/home/ubuntu/ai/ComfyUI/venv/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[comfy_mtb] | INFO -> loaded 93 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://None:8188/mtb if you want more information.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.7-43-gd6656b0 | Released on '2024-12-17'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
[ReActor] - STATUS - Running v0.5.2-a2 in ComfyUI
Torch version: 2.5.0+cu124
[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉
[ComfyUI Model Manager] current version 2.1.6, web version 2.1.1
[ComfyUI Model Manager] Downloading web distribution...
[ComfyUI Model Manager] Extracting web distribution...
[ComfyUI Model Manager] Web distribution downloaded successfully.
Total VRAM 22503 MB, total RAM 63592 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10G : cudaMallocAsync
[tinyterraNodes] Loaded
here: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-tbox
Using ckpts path: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotator
Using symlinks: False
Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
Loaded Efficiency nodes from /home/ubuntu/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V8.0.1)
### Loading: ComfyUI-Impact-Pack (V8.0.1)
Loaded ImpactPack nodes from [Impact Pack] Wildcards loading done./home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/ubuntu/ai/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.
        "The only person you should try to be better than is the person you were yesterday." - Unknown
@@device:cuda
@@device:cuda
Please 'pip install xformers'
Nvidia APEX normalization not installed, using PyTorch LayerNorm
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
[ComfyUI-Easy-Use] server: v1.2.6 Loaded
[ComfyUI-Easy-Use] web root: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Easy-Use/web_version/v2 Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD EPYC 7R32 - Arch: x86_64 - OS: Linux 6.8.0-1017-aws
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA A10G
[Crystools INFO] NVIDIA Driver: 550.90.07
### Loading: ComfyUI-Inspire-Pack (V1.9)
Import times for custom nodes:
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/Bobs_Latent_Optimizer.py
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-IC-Light-Native
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/image-resize-comfyui
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/cemil-nodes
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/CharacterFaceSwap
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-BRIA_AI-RMBG
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_yanc
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/civitai_comfy_nodes
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_InstantID
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-ipadapter-flux
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyMath
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-IC-Light
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Florence2
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-browser
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/x-flux-comfyui
   0.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-GGUF
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-liveportrait
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Crystools
   0.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/antrobots-comfyUI-nodepack
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_Sapiens
   0.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/PuLID_ComfyUI
   0.4 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Manager
   0.4 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.6 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-reactor-node
   0.7 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   0.8 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui-art-venture
   0.8 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-tbox
   1.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Gemini
   1.0 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfyui_segment_anything
   1.2 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Model-Manager
   1.5 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   2.5 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/comfy_mtb
   3.1 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/was-node-suite-comfyui
   3.5 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI_LayerStyle
   3.7 seconds: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-SUPIR
Starting server
To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: /home/ubuntu/ai/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
QualityOfLifeSuit_Omar92::NSP ready
```

```
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/ai/ComfyUI/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/venv/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/custom_nodes/comfy_mtb/__init__.py", line 550, in do_action
    return await endpoint.do_action(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/custom_nodes/comfy_mtb/endpoint.py", line 169, in do_action
    result = method(*args) if isinstance(args, list) else method(args)
             ^^^^^^^^^^^^^
  File "/home/ubuntu/ai/ComfyUI/custom_nodes/comfy_mtb/endpoint.py", line 103, in ACTIONS_getUserImages
    if offset <= i < offset + count
                     ~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by melMass** [comment]
Thanks for the report! This is a dumb mistake on my end, one of those folder (input or output) is empty... 
I will fix it but in the meantime just make sure to have at least one image in either folder
