### ISSUE TITLE
(mac)执行comfy_mtb插件的 浏览输入和输出目录 报错[bug] 

### ISSUE THREAD

**Issue by BannyLon** [melMass/comfy_mtb#225]
### Describe the bug

我电脑上 mac ，comfyui是源码本地配置，在使用最新的comfy_mtb插件执行MTB: Browse inputsand outputs directories.时，一直出现TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'报错。
![1734666554207](https://github.com/user-attachments/assets/3f7c7f42-d358-4c81-8de7-708ea08853bf)

### Operating System

Mac

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/photoswipe-lightbox.esm.min.js
FETCH DATA from: /Users/habhy/Sites/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/photoswipe.min.css
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/pickr.min.js
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/model-viewer.min.js
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/classic.min.css
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/juxtapose.min.js
/Users/habhy/Sites/ComfyUI/custom_nodes/comfyui-mixlab-nodes/webApp/lib/juxtapose.css
Error handling request
Traceback (most recent call last):
  File "/Users/habhy/Sites/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/custom_nodes/comfy_mtb/__init__.py", line 550, in do_action
    return await endpoint.do_action(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/custom_nodes/comfy_mtb/endpoint.py", line 169, in do_action
    result = method(*args) if isinstance(args, list) else method(args)
             ^^^^^^^^^^^^^
  File "/Users/habhy/Sites/ComfyUI/custom_nodes/comfy_mtb/endpoint.py", line 96, in ACTIONS_getUserImages
    imgs = {
           ^
  File "/Users/habhy/Sites/ComfyUI/custom_nodes/comfy_mtb/endpoint.py", line 103, in <dictcomp>
    if offset <= i < offset + count
                     ~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

### Additional context

我自己已经得到了修复，希望插件作者能看到。是否在main分支进行修改。具体修改方法我放在了：https://www.bilibili.com/opus/1012884576977027079

**Comment by melMass** [comment]
Hey I just pushed a fix, let me know if it's fixed for you.

**Comment by BannyLon** [comment]
还有一个问题，比如我热点放在（MTB: Browse inputsand outputs directories.）上，但我想切换到（管理节点组）或者（工作流）上，就要点击两次。但是如果是（管理节点组）与（工作流）之间切换就很丝滑。这一定是一个问题？还望解决。谢谢！
