### ISSUE TITLE
[bug] SAVE GIF

### ISSUE THREAD

**Issue by bytecann** [melMass/comfy_mtb#60]
### Describe the bug

![MTB-Deforum-test](https://github.com/melMass/comfy_mtb/assets/138059263/8a4c69c5-9875-49b3-b386-020617b3caf2)
At the end of running the 04-animation_builder-deforum.jsom example, I get this error message

### Expected behavior

I expected a GIF file to be saved in the output folder

### Platform and versions

```sh
Windows 10
```

### Console output

```sh
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\io.py", line 155, in save_gif
    process = subprocess.Popen(command, stdin=subprocess.PIPE)
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

Prompt executed in 1.39 seconds
```

**Comment by melMass** [comment]
The version currently in main uses FFMPEG, so it's expected to be available on path. That said I'm switching method in #50 to avoid the need for ffmpeg!
It should be in the release tonight

**Comment by bytecann** [comment]
Thank you… I fixed the issue by making sure FFmpeg was in the system path. It now works perfect.

**Comment by melMass** [comment]
Nice, the reason for the switch from ffmpeg is mostly size and quality, results look better using PIL only
