### ISSUE TITLE
[bug] Python < 3.10 support?

### ISSUE THREAD

**Issue by voroninvisuals** [melMass/comfy_mtb#61]
### Describe the bug

Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/comfy_mtb/__init__.py", line 18, in <module>
    from .utils import here
  File "/notebooks/ComfyUI/custom_nodes/comfy_mtb/utils.py", line 96, in <module>
    def pil2tensor(image: Image.Image | List[Image.Image]) -> torch.Tensor:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

Cannot import /notebooks/ComfyUI/custom_nodes/comfy_mtb module for custom nodes: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### Platform and versions

```sh
paperspace
```

**Comment by melMass** [comment]
From the error I guess you are using python 3.9 or lower?

**Comment by melMass** [comment]
I'm closing as there was no update, but feel free to comment with the details asked and I'll reopen it
